version: "3"

services:
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "4000:80"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data: {}